name: Build CelesteTAS + Studio

on:
  workflow_call:
  push:
    branches:
      - '*'
    paths:
      - 'CelesteTAS-EverestInterop/**'
      - 'Studio/**'
      - 'StudioCommunication/**'
      - .github/workflows/CelesteStudio.Build.yml
  pull_request:
    branches:
      - '*'
    paths:
      - 'CelesteTAS-EverestInterop/**'
      - 'Studio/**'
      - 'StudioCommunication/**'
      - .github/workflows/CelesteStudio.Build.yml

jobs:
  build-studio:
    uses: ./.github/workflows/Build.CelesteStudio.yml
    with:
      build-cfg: Debug

  build-celestetas:
    runs-on: ubuntu-latest
    needs: build-studio

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Download Windows x64
        uses: actions/download-artifact@v4
        with:
          name: CelesteStudio-windows-x64
          path: CelesteStudio-windows-x64
      - name: Download Linux x64
        uses: actions/download-artifact@v4
        with:
          name: CelesteStudio-linux-x64
          path: CelesteStudio-linux-x64
      - name: Download OSX x64
        uses: actions/download-artifact@v4
        with:
          name: CelesteStudio-osx-x64
          path: CelesteStudio-osx-x64

      # download-artifact automatically unzips them, so we need to re-zip
      - name: Re-zip artifacts
        run: |
          pushd CelesteStudio-windows-x64
          zip CelesteStudio-windows-x64.zip **
          popd
          pushd CelesteStudio-linux-x64
          zip CelesteStudio-linux-x64.zip **
          popd
          pushd CelesteStudio-osx-x64
          zip CelesteStudio-osx-x64.zip **
          popd

      - name: Describe Git history
        id: ghd
        uses: proudust/gh-describe@v2

      - name: Fill-in download info
        run: |
          sed -i "s\\##STUDIO_VERSION##\\${{ steps.ghd.outputs.describe }}\\" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s\\##URL_WINDOWS_x64##\\https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/CelesteStudio-windows-x64.zip\\" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s\\##URL_LINUX_x64##\\https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/CelesteStudio-linux-x64.zip\\" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s\\##URL_OSX_x64##\\https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/CelesteStudio-osx-x64.zip\\" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s\\##CHECKSUM_WINDOWS_x64##\\$(md5sum CelesteStudio-windows-x64/CelesteStudio-windows-x64.zip | head -c 32)\\" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s\\##CHECKSUM_LINUX_x64##\\$(md5sum CelesteStudio-linux-x64/CelesteStudio-linux-x64.zip | head -c 32)\\" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs
          sed -i "s\\##CHECKSUM_OSX_x64##\\$(md5sum CelesteStudio-osx-x64/CelesteStudio-osx-x64.zip | head -c 32)\\" CelesteTAS-EverestInterop/EverestInterop/StudioHelper.cs

      - name: Build
        run: dotnet build CelesteTAS-EverestInterop -c Debug -p:DefineConstants=INSTALL_STUDIO

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CelesteTAS
          path: |
            everest.yaml
            bin
            Dialog
