name: Release

on:
  workflow_dispatch: 
  push:
    tags:
      - "v*.*.*"

jobs:
  build-studio:
    uses: ./.github/workflows/CelesteStudio.Build.yml
  
  release:
    runs-on: ubuntu-latest
    needs: [build-studio]

    steps:
      - name: Download studio artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ needs.build-studio.outputs.runid }}
        
      - name: Calculate MD5 checksums
        run: |
          md5sum CelesteStudio-windows-x64.zip
          md5sum CelesteStudio-windows-arm64.zip
          md5sum CelesteStudio-linux-x64.zip
          md5sum CelesteStudio-linux-arm.zip
          md5sum CelesteStudio-linux-arm64.zip
          md5sum CelesteStudio-osx-x64.zip
          md5sum CelesteStudio-osx-arm64.zip
      
      # TOOD: Embed the MD5 checksums into CelesteTAS before building and create a release
      
#      - name: Create Release
#        uses: marvinpinto/action-automatic-releases@latest
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          prerelease: false
#          files: CelesteTAS_${{github.ref_name}}.zip